// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"directBTC/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/task/bind",
				Handler: BindEvmAddressHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/task/list",
				Handler: GetTaskListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/btc/address/transactionHistory",
				Handler: GetBtcAddressTransactionHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/btc/address/trialComplete",
				Handler: GetBtcAddressIsTrialHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
